//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CajaPopular
{
    using System;
    using System.Collections.Generic;
    
    public partial class contrato
    {
        public string uid { get; set; }
        public int id_solicitud { get; set; }
        public int id_solicitante { get; set; }
        public int id_aval { get; set; }
    
        public virtual rel_solicitante_aval rel_solicitante_aval { get; set; }
    }
}
