//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CajaPopular
{
    using System;
    using System.Collections.Generic;
    
    public partial class formato_contrato
    {
        public string encabezado { get; set; }
        public string d_primera { get; set; }
        public string d_segunda { get; set; }
        public string d_tercera { get; set; }
        public string d_tercera2 { get; set; }
        public string d_tercera3 { get; set; }
        public string c_primera { get; set; }
        public string c_segunda { get; set; }
        public string c_segunda1 { get; set; }
        public string c_tercera1 { get; set; }
        public string c_tercera2 { get; set; }
        public string c_cuarta { get; set; }
        public string c_quinta { get; set; }
        public string c_sexta { get; set; }
        public string c_septima { get; set; }
        public string c_octava { get; set; }
        public string c_novena { get; set; }
        public string c_decima { get; set; }
        public string c_decimoprimera { get; set; }
        public string c_decimosegunda { get; set; }
        public string c_decimotercera { get; set; }
        public string c_decimocuarta { get; set; }
        public string c_decimoquinta { get; set; }
        public int id { get; set; }
    }
}
