//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CajaPopular
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class caja_popular2Entities : DbContext
    {
        public caja_popular2Entities()
            : base("name=caja_popular2Entities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<aval> avals { get; set; }
        public virtual DbSet<balance> balances { get; set; }
        public virtual DbSet<contrato> contratoes { get; set; }
        public virtual DbSet<cotizacion> cotizacions { get; set; }
        public virtual DbSet<persona> personas { get; set; }
        public virtual DbSet<plazo> plazoes { get; set; }
        public virtual DbSet<rel_solicitante_aval> rel_solicitante_aval { get; set; }
        public virtual DbSet<solicitante> solicitantes { get; set; }
        public virtual DbSet<solicitud> solicituds { get; set; }
        public virtual DbSet<tasa> tasas { get; set; }
        public virtual DbSet<usuario> usuarios { get; set; }
        public virtual DbSet<formato_contrato> formato_contrato { get; set; }
    }
}
