//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CajaPopular
{
    using System;
    using System.Collections.Generic;
    
    public partial class solicitud
    {
        public int uid { get; set; }
        public int id_solicitante { get; set; }
        public System.DateTime fecha { get; set; }
        public Nullable<decimal> cantidad_solicitada { get; set; }
        public Nullable<int> plazo_solicitado { get; set; }
        public Nullable<decimal> cantidad_maxima { get; set; }
        public string finalidad { get; set; }
        public string entrega_prestamo { get; set; }
        public string clave_interbancaria { get; set; }
        public string tipo_prestamo { get; set; }
        public string estatus { get; set; }
        public Nullable<decimal> monto_autorizado { get; set; }
        public Nullable<int> plazo_autorizado { get; set; }
        public Nullable<System.DateTime> fecha_resolucion { get; set; }
        public Nullable<int> responsable_autorizacion { get; set; }
    
        public virtual solicitante solicitante { get; set; }
    }
}
