//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CajaPopular
{
    using System;
    using System.Collections.Generic;
    
    public partial class usuario
    {
        public usuario()
        {
            this.balances = new HashSet<balance>();
        }
    
        public int uid { get; set; }
        public Nullable<int> id_persona { get; set; }
        public string departamento { get; set; }
        public string usuario1 { get; set; }
        public string contraseña { get; set; }
        public string grupo { get; set; }
        public string rol { get; set; }
    
        public virtual ICollection<balance> balances { get; set; }
    }
}
